### ISSUE TITLE
Does not run on ARM (Apple Silicon)

### ISSUE THREAD

**Issue by anuragrao04** [acmpesuecc/ResourcePolice#27]
Attempting to run on Apple Silicon returns the below error
```
_______________________________________________________________________________________
    ____                                               ____
    /    )                                             /    )         /   ,
---/___ /----__---__----__----------)__----__----__---/____/----__---/--------__----__-
  /    |   /___) (_ ` /   ) /   /  /   ) /   ' /___) /        /   ) /   /   /   ' /___)
_/_____|__(___ _(__)_(___/_(___(__/_____(___ _(___ _/________(___/_/___/___(___ _(___ _




==================================================
               System Information:
==================================================
System: Darwin
Node Name: Anurags-MacBook-Air.local
Release: 21.6.0
Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101
Machine: x86_64
Processor: i386


==================================================
                System Resources:
==================================================
==================================================
Memory usage   CPU usage  Disk usage
==================================================
92.2                17.1        53.2
Traceback (most recent call last):
  File "/Users/anuragrao/git_clones/ResourcePolice/RP.py", line 105, in <module>
    start()
  File "/Users/anuragrao/git_clones/ResourcePolice/RP.py", line 47, in start
    memNotif()
  File "/Users/anuragrao/git_clones/ResourcePolice/RP.py", line 67, in memNotif
    plyer.notification.notify("ResourcePolice", "Memory Usage high!", timeout=10)
  File "/Users/anuragrao/.pyenv/versions/3.9.13/lib/python3.9/site-packages/plyer/facades/notification.py", line 79, in notify
    self._notify(
  File "/Users/anuragrao/.pyenv/versions/3.9.13/lib/python3.9/site-packages/plyer/platforms/macosx/notification.py", line 38, in _notify
    usrnotifctr.setDelegate_(self)
AttributeError: 'NoneType' object has no attribute 'setDelegate_'
```

**Comment by ad-chaos** [comment]
try `pip install pyobjus` and then run it again
